### ISSUE TITLE
Ability to open multiple NWB files at the same time

### ISSUE THREAD

**Issue by anilbey** [brainhack-ch/nwbview#11]

**Comment by adrien-berchet** [comment]
Should be fixed by #17

**Comment by adrien-berchet** [comment]
But we need to improve the UI to make it more usable

**Comment by adrien-berchet** [comment]
I think we should create several specific sub-window (of `Box` type I think?) to create a proper layout. For example, we could create a sub-window for the tree view of the files and their groups / datasets, so it will be easy to add a scroll bar on this area. The rest of the window could be dedicated to the plots. Maybe we could even create one `Box` per file and then the plots inside each `Box`. WDYT @anilbey ?

**Comment by anilbey** [comment]
A very good idea to have a sub-window and scroll bar.
