### ISSUE TITLE
Create a logo for nwbview

### ISSUE THREAD

**Issue by anilbey** [brainhack-ch/nwbview#12]
How about one of the 2 icons? Which one do you like more @adrien-berchet @crisely09 @rai-pranav @JCGoran ?

# 1) A rusted morphological neuron logo with blank  background
![00007-2920456485-a rusted morphological neuron logo with blank  background](https://user-images.githubusercontent.com/7026020/216715560-5e745eb8-c84c-43f0-a75e-d90d2429fcfc.png)

# 1) Updated: Removed white background
![00007-2920456485-a_rusted_morphological_neuron_logo_with_blank__background-removebg-preview](https://user-images.githubusercontent.com/7026020/216720416-4acac52e-05f1-4d63-b964-edd454ffe0a3.png)

# 2) Rusted neuron with blank background, logo
![00017-3121124550-rusted neuron with blank background, logo](https://user-images.githubusercontent.com/7026020/216715564-98abdf75-9836-48bd-bb40-77c6dcb6d8b3.png)

**Comment by adrien-berchet** [comment]
I vote 1. I am not sure about the white background though.

**Comment by anilbey** [comment]
It seems there's an online service to remove the white background :D

![00007-2920456485-a_rusted_morphological_neuron_logo_with_blank__background-removebg-preview](https://user-images.githubusercontent.com/7026020/216720163-8b5feb57-f254-4d14-9173-5d4dcb0a00f0.png)

credits: 
https://www.remove.bg/

**Comment by adrien-berchet** [comment]
I really like this one 🤩
Very nice work @anilbey , thanks!

**Comment by rai-pranav** [comment]
I also like the first one. Did you generate this with text to image generation?

**Comment by JCGoran** [comment]
I'm also inclined to go with the first one, though they both look awesome!

**Comment by anilbey** [comment]
@rai-pranav 
> Did you generate this with text to image generation?

@darshanmandge generated the first image using Stable Diffusion.

**Comment by anilbey** [comment]
I also liked the first one more.

**Comment by crisely09** [comment]
oh, I like 2 better, but I trust the majority.
