### ISSUE TITLE
nwbview does not launch from Terminal on mac os Ventura 13.2.1

### ISSUE THREAD

**Issue by darshanmandge** [brainhack-ch/nwbview#33]
1. I get this error when I try to launch nwbview from terminal:

`thread 'main' panicked at 'Failed to open icon path: IoError(Os { code: 2, kind: NotFound, message: "No such file or directory" })', /Users/abc/.cargo/registry/src/github.com-1ecc6299db9ec823/nwbview-0.2.3/src/main.rs:11:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

@anilbey, however, managed to run it when the terminal was in working directory mentioned in the error.

2. The icon does not show in the GUI and also on the dock when opened (Currently dock icon is a black terminal).

Thanks.

**Comment by anilbey** [comment]
Thanks @darshanmandge for reporting this. We will have a look into it.

Different operating systems have different ways of storing the rust binaries and static files it seems. One safe solution can be to launch the app without the icon when the icon cannot be found.

Related questions to consider:
* Is this a common issue in all mac OS or only in the latest version?
* Can there be a common solution to load static files from cargo installed packages for all mac OS?
* How about Windows?

**Comment by anilbey** [comment]
It's fixed now. Thanks Darshan for reporting.
